version: "3.9"

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=vdcd
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  minio:
    image: minio/minio
    hostname: "minio"
    env_file:
      - minio.env
    command: "minio server /minio_files"
    ports:
      - 9000:9000
    healthcheck:
      test: "curl -I --fail --max-time 10 http://localhost:9000/minio/health/live"
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 3
  api:
    build: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    env_file:
      - keycloak.env
      - minio.env
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db
      - DB_NAME=vdcd
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DJANGO_DEBUG=True
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    healthcheck:
      test: "curl --fail --max-time 5 http://localhost:8000/healthcheck"
      start_period: 15s
      interval: 15s
      timeout: 10s
      retries: 2
    depends_on:
      db:
        condition: service_healthy
      minio:
        condition: service_healthy
  workers:
    build: ./backend
    command: >
      sh -c "python manage.py qcluster"
    env_file:
      - minio.env
    environment:
      - DB_ENGINE=django.db.backends.postgresql
      - DB_HOST=db
      - DB_NAME=vdcd
      - DB_PASSWORD=postgres
      - DB_PORT=5432
      - DB_USER=postgres
      - DJANGO_DEBUG=True
    volumes:
      - ./backend:/backend
    depends_on:
      api:
        condition: service_healthy
  web:
    build: ./frontend
    command: npm run start
    volumes:
      - ./frontend:/web
      - /web/node_modules
    ports:
      - 3000:3000
